### ISSUE TITLE
question

### ISSUE THREAD

**Issue by 1994sunshine** [vis-three/exhibition-hall#1]
你好，里面的示例代码是打包好的，没有相关可以阅读的代码。

**Comment by Shiotsukikaedesari** [comment]
本仓库是用来展示vis-three框架衍生编辑器的生产项目的展示库。
vis-three框架：https://github.com/vis-three/vis-three
【vis-three】scene-editor：https://github.com/vis-three/scene-editor
框架介绍与产品演示：https://space.bilibili.com/3048588
